In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import GaussianNB

In [2]:
datasetRaw=pd.read_csv("flag.csv")

In [3]:
datasetRaw.drop(['name',"area","population"],axis=1,inplace=True)

In [4]:
ycolumns=["landmass","zone","language","religion"]

In [5]:
x=datasetRaw.drop(ycolumns,axis=1)

In [6]:
toplefts=x["topleft"].unique()
topleftsNum=[i+1 for i in range(len(toplefts))]
x["topleft"].replace(toplefts,topleftsNum,inplace=True)

botrights=x["botright"].unique()
botrightsNum=[i+1 for i in range(len(botrights))]
x["botright"].replace(botrights,botrightsNum,inplace=True)

mainhues=x["mainhue"].unique()
mainhuesNum=[i+1 for i in range(len(mainhues))]
x["mainhue"].replace(mainhues,mainhuesNum,inplace=True)




In [7]:
sc_X=MinMaxScaler()

In [8]:
for s in range(4):
    y=datasetRaw.iloc[:,s]
    print(ycolumns[s])
    X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.20, random_state=56)
    X_train_S=sc_X.fit_transform(X_train)
    X_test_S=sc_X.fit_transform(X_test)
  
    classifier = GaussianNB()
    classifier.fit(X_train_S, y_train)
    
    y_pred = classifier.predict(X_test_S)
    
    a=accuracy_score(y_test, y_pred)
    print("Başarım:",a)
    
    cm = confusion_matrix(y_test, y_pred)
    print(cm)

landmass
Başarım: 0.28205128205128205
[[1 0 4 0 3 0]
 [0 0 3 0 1 0]
 [0 1 4 0 1 0]
 [0 0 3 0 1 2]
 [0 2 2 0 2 0]
 [1 1 1 0 2 4]]
zone
Başarım: 0.2564102564102564
[[9 0 5 0]
 [5 0 3 1]
 [3 0 1 0]
 [9 0 3 0]]
language
Başarım: 0.23076923076923078
[[5 2 0 0 0 1 0 1 1 1]
 [1 0 2 2 0 0 0 0 0 0]
 [0 0 3 0 0 0 0 1 0 1]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 1 0]
 [0 1 1 1 0 0 0 0 1 0]
 [2 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [1 1 1 2 0 0 0 3 1 0]]
religion
Başarım: 0.1282051282051282
[[1 0 0 3 2 0 1 4]
 [3 4 0 1 1 0 2 1]
 [0 0 0 1 0 0 1 2]
 [0 1 0 0 1 0 0 1]
 [0 0 0 0 0 0 0 0]
 [0 1 0 0 2 0 2 1]
 [0 0 0 0 1 0 0 2]
 [0 0 0 0 0 0 0 0]]


# Normalizasyonsuz

In [9]:
for s in range(4):
    y=datasetRaw.iloc[:,s]
    print(ycolumns[s])
    X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.20, random_state=56)
    
  
    classifier = GaussianNB()
    classifier.fit(X_train, y_train)
    
    y_pred = classifier.predict(X_test)
    
    a=accuracy_score(y_test, y_pred)
    print("Başarım:",a)
    
    cm = confusion_matrix(y_test, y_pred)
    print(cm)

landmass
Başarım: 0.28205128205128205
[[1 0 3 0 2 2]
 [0 0 4 0 0 0]
 [1 0 4 0 0 1]
 [0 0 5 0 0 1]
 [0 0 3 0 1 2]
 [0 0 2 0 2 5]]
zone
Başarım: 0.3076923076923077
[[11  0  3  0]
 [ 7  0  2  0]
 [ 3  0  1  0]
 [10  0  2  0]]
language
Başarım: 0.20512820512820512
[[4 1 1 0 0 2 0 2 1 0]
 [0 0 2 2 0 0 0 0 1 0]
 [0 0 3 0 0 1 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 1 1 0 0 0 0 0 0]
 [0 1 1 1 0 0 0 0 1 0]
 [1 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 1 2 2 1 0 0 2 1 0]]
religion
Başarım: 0.07692307692307693
[[0 0 0 2 4 0 1 4]
 [2 3 0 1 2 0 3 1]
 [0 0 0 1 0 0 1 2]
 [0 1 0 0 1 0 0 1]
 [0 0 0 0 0 0 0 0]
 [1 0 0 0 2 0 2 1]
 [0 0 0 0 1 0 0 2]
 [0 0 0 0 0 0 0 0]]
