In [1]:
from sklearn import datasets
import pandas as pd
import numpy as np
iris=datasets.load_iris()

In [2]:
x=iris.data
y=iris.target

In [3]:
xp=pd.DataFrame(x,columns=["sepal_length","sepal_width","petal_length","pedal_width"])
yp=pd.DataFrame(y,columns=["Class"])
yp.head()

Class
0      0
1      0
2      0
3      0
4      0

In [4]:
xp.head()

sepal_length  sepal_width  petal_length  pedal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [5]:
maksimumlar=xp.max() #hepsinin maximumu
minimumlar=xp.min()
birimparca=(maksimumlar-minimumlar)/3
print(birimparca)
ilksinir=minimumlar+birimparca
print(ilksinir)
ikincisinir=maksimumlar-birimparca
print(ikincisinir)

sepal_length    1.200000
sepal_width     0.800000
petal_length    1.966667
pedal_width     0.800000
dtype: float64
sepal_length    5.500000
sepal_width     2.800000
petal_length    2.966667
pedal_width     0.900000
dtype: float64
sepal_length    6.700000
sepal_width     3.600000
petal_length    4.933333
pedal_width     1.700000
dtype: float64


In [6]:
kategorik=pd.DataFrame()
labels = [0,1,2]

for i in range(4):
  bins = [-np.inf,ilksinir[i], ikincisinir[i], np.inf]    
  temp = pd.cut(xp.iloc[:,i], bins=bins, labels=labels)
  kategorik[xp.columns[i]+"_ktgri"]=temp
kategorik.head()

sepal_length_ktgri sepal_width_ktgri petal_length_ktgri pedal_width_ktgri
0                  0                 1                  0                 0
1                  0                 1                  0                 0
2                  0                 1                  0                 0
3                  0                 1                  0                 0
4                  0                 1                  0                 0

In [7]:
data=kategorik
data["Class"]=yp
data.head()

sepal_length_ktgri sepal_width_ktgri petal_length_ktgri pedal_width_ktgri  \
0                  0                 1                  0                 0   
1                  0                 1                  0                 0   
2                  0                 1                  0                 0   
3                  0                 1                  0                 0   
4                  0                 1                  0                 0   

   Class  
0      0  
1      0  
2      0  
3      0  
4      0

In [8]:
y=data["Class"]
X=data.drop("Class",axis=1)

In [9]:
'''from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)'''

'from sklearn.model_selection import train_test_split\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)'

In [10]:
X_train= X_test=x
y_train= y_test=y

In [11]:
from sklearn.tree import DecisionTreeClassifier 
classifier = DecisionTreeClassifier(criterion = 'gini', random_state=0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(random_state=0)

In [12]:
y_pred = classifier.predict(X_test)

In [13]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[50  0  0]
 [ 0 50  0]
 [ 0  0 50]]


In [14]:
from sklearn.metrics import accuracy_score
a=accuracy_score(y_test, y_pred)
print("Başarım:",a)

Başarım: 1.0


In [15]:
'classifier.tree_?

In [16]:
'DecisionTreeClassifier?

In [17]:
classifier.tree_.impurity

array([0.66666667, 0.        , 0.5       , 0.16803841, 0.04079861,
       0.        , 0.        , 0.44444444, 0.        , 0.44444444,
       0.        , 0.        , 0.04253308, 0.44444444, 0.        ,
       0.        , 0.        ])

In [18]:
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state=0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [19]:
classifier.tree_.impurity

array([1.5849625 , 0.        , 1.        , 0.44506486, 0.14609425,
       0.        , 0.        , 0.91829583, 0.        , 0.91829583,
       0.        , 0.        , 0.15109697, 0.91829583, 0.        ,
       0.        , 0.        ])

In [20]:
classifier = DecisionTreeClassifier(criterion = 'log_loss', random_state=0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(criterion='log_loss', random_state=0)

In [21]:
classifier.tree_.impurity

array([1.5849625 , 0.        , 1.        , 0.44506486, 0.14609425,
       0.        , 0.        , 0.91829583, 0.        , 0.91829583,
       0.        , 0.        , 0.15109697, 0.91829583, 0.        ,
       0.        , 0.        ])