# NUMPY İNDEKSLEME

In [1]:
import numpy as np

# Tek Boyutlu Array

In [4]:
a = np.arange(10)**2

In [5]:
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [6]:
a[3]

9

In [7]:
a[3:6]

array([ 9, 16, 25])

In [8]:
a[4] = 1000
a

array([   0,    1,    4,    9, 1000,   25,   36,   49,   64,   81])

In [9]:
for i in a:
    print(i*2)

0
2
8
18
2000
50
72
98
128
162


# Çok Boyutlu Array

In [10]:
y = np.random.random(16)

In [11]:
y

array([0.08298171, 0.10208992, 0.15736916, 0.76098216, 0.09874606,
       0.92167668, 0.10616098, 0.61526761, 0.89941989, 0.77175787,
       0.60897332, 0.32567379, 0.74904727, 0.72536757, 0.8226414 ,
       0.09262429])

In [12]:
y = y.reshape(4,4)
y

array([[0.08298171, 0.10208992, 0.15736916, 0.76098216],
       [0.09874606, 0.92167668, 0.10616098, 0.61526761],
       [0.89941989, 0.77175787, 0.60897332, 0.32567379],
       [0.74904727, 0.72536757, 0.8226414 , 0.09262429]])

In [13]:
y.ravel()

array([0.08298171, 0.10208992, 0.15736916, 0.76098216, 0.09874606,
       0.92167668, 0.10616098, 0.61526761, 0.89941989, 0.77175787,
       0.60897332, 0.32567379, 0.74904727, 0.72536757, 0.8226414 ,
       0.09262429])

In [14]:
y[0:2,1]

array([0.10208992, 0.92167668])

In [15]:
y[:,3]

array([0.76098216, 0.61526761, 0.32567379, 0.09262429])

In [16]:
for satır in y:
    print(satır)

[0.08298171 0.10208992 0.15736916 0.76098216]
[0.09874606 0.92167668 0.10616098 0.61526761]
[0.89941989 0.77175787 0.60897332 0.32567379]
[0.74904727 0.72536757 0.8226414  0.09262429]


In [17]:
for satır in y.flat:
    print(satır)

0.08298170597852095
0.10208991505594622
0.1573691566941421
0.7609821574613806
0.09874606107878492
0.9216766798718515
0.10616098308931043
0.6152676119954407
0.8994198942240106
0.7717578735760396
0.6089733214433387
0.32567378729416907
0.7490472668353779
0.7253675692631788
0.822641403079972
0.09262429409959727


In [19]:
for satır in np.ndenumerate(y):
    print(satır)

((0, 0), 0.08298170597852095)
((0, 1), 0.10208991505594622)
((0, 2), 0.1573691566941421)
((0, 3), 0.7609821574613806)
((1, 0), 0.09874606107878492)
((1, 1), 0.9216766798718515)
((1, 2), 0.10616098308931043)
((1, 3), 0.6152676119954407)
((2, 0), 0.8994198942240106)
((2, 1), 0.7717578735760396)
((2, 2), 0.6089733214433387)
((2, 3), 0.32567378729416907)
((3, 0), 0.7490472668353779)
((3, 1), 0.7253675692631788)
((3, 2), 0.822641403079972)
((3, 3), 0.09262429409959727)


In [20]:
a = np.array([2,3])
b = np.array([5,6])

In [21]:
np.hstack((a,b))

array([2, 3, 5, 6])

In [22]:
np.vstack((a,b))

array([[2, 3],
       [5, 6]])

In [23]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])
np.concatenate((a,b),axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [24]:
np.concatenate((a,b.T),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])