# NUMPY ARRAY OLUŞTURMA

In [1]:
import numpy as np

In [4]:
x = np.array([1,2,3,4])

In [5]:
type(x)

numpy.ndarray

In [8]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
np.ones((2,4))*5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [31]:
n = np.arange(10,50,5)
n

array([10, 15, 20, 25, 30, 35, 40, 45])

In [13]:
ondalık = np.arange(0,2,0.2)
ondalık

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8])

In [14]:
lin = np.linspace(0,4,12)
lin

array([0.        , 0.36363636, 0.72727273, 1.09090909, 1.45454545,
       1.81818182, 2.18181818, 2.54545455, 2.90909091, 3.27272727,
       3.63636364, 4.        ])

In [15]:
rast = np.random.rand(3,4)
rast

array([[0.4170675 , 0.516525  , 0.71706898, 0.74393838],
       [0.72085597, 0.58094329, 0.36382176, 0.45737267],
       [0.00468606, 0.85173949, 0.17970836, 0.51477931]])

In [17]:
n = np.random.randn(2,5)*5
n

array([[-2.9130464 , -4.52130241, -7.30967902, -7.02169216, -5.91923697],
       [-1.21777631, -2.83357363,  5.76785137, -7.16576617,  5.82219588]])

In [18]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [32]:
c= np.random.randint(1,50,15)
c

array([36, 43, 32, 24,  1, 44, 34,  8, 32, 10, 41,  9, 24, 43, 19])

In [33]:
y = np.arange(24)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [34]:
y.reshape(6,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [35]:
y.reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [36]:
c.max()

44

In [37]:
c.min()

1

In [38]:
c.argmax()

5

In [39]:
c.argmin()

4

In [40]:
a = np.arange(50)
a.shape = 2,-1,5
a.shape

(2, 5, 5)

In [41]:
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])