# NUMPY İŞLEMLER 

In [1]:
import numpy as np

In [2]:
a = np.array([20,40,60,80])
a

array([20, 40, 60, 80])

In [3]:
b= np.arange(4)
b

array([0, 1, 2, 3])

In [4]:
c = a+b
c

array([20, 41, 62, 83])

In [5]:
a**2

array([ 400, 1600, 3600, 6400])

In [6]:
a>50

array([False, False,  True,  True])

In [7]:
a += 10

In [8]:
a

array([30, 50, 70, 90])

In [9]:
x = np.random.random(12)
x

array([0.71044879, 0.73268103, 0.48517848, 0.43251212, 0.33350035,
       0.2949761 , 0.37529818, 0.27634402, 0.22504661, 0.69112564,
       0.42083675, 0.14712355])

In [10]:
x.max()

0.732681034074037

In [11]:
x.min()

0.14712354831478658

In [12]:
x.sum()

5.125071623994144

In [13]:
b = np.arange(15).reshape(3,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [14]:
b.sum(axis = 0)

array([15, 18, 21, 24, 27])

In [15]:
b.sum(axis = 1)

array([10, 35, 60])

In [16]:
b.max(axis = 1)

array([ 4,  9, 14])

In [18]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6, 10],
       [ 5, 11, 18, 26, 35],
       [10, 21, 33, 46, 60]])

In [19]:
k = np.random.random(10)

In [20]:
k

array([0.17009139, 0.18595428, 0.54925117, 0.2603186 , 0.51747928,
       0.05819456, 0.14642098, 0.62947731, 0.20819745, 0.38718749])

In [21]:
k.mean()

0.3112572506354816

In [23]:
np.median(k)

0.23425802314240235

In [24]:
np.std(k)

0.186079140406567

In [25]:
np.var(k)

0.034625446494446876

In [26]:
kopya = k.copy()

In [27]:
kopya

array([0.17009139, 0.18595428, 0.54925117, 0.2603186 , 0.51747928,
       0.05819456, 0.14642098, 0.62947731, 0.20819745, 0.38718749])

In [28]:
şehir = np.array(["ankara","istanbul","bursa","ankara","izmir","bursa","izmir"])
np.unique(şehir)

array(['ankara', 'bursa', 'istanbul', 'izmir'], dtype='<U8')